language: python

install:
- pip install pelican markdown

script:
- pelican content -s publishconf.py

# Thanks to Thomas Parisot for the following deployment strategy as
# described at https://oncletom.io/2016/travis-ssh-deploy/.

addons:
  ssh_known_hosts: con.cor.dance

before_deploy:
- openssl aes-256-cbc -K $encrypted_a71e11f2943c_key -iv $encrypted_a71e11f2943c_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/output/ ben@con.cor.dance:html
  on:
    branch: master
